const JOKERS_MAP = {
  NONE: "None",
  EIGHT_BALL: "8 Ball",
  ABSTRACT_JOKER: "Abstract Joker",
  ACROBAT: "Acrobat",
  ANCIENT_JOKER: "Ancient Joker",
  ARROWHEAD: "Arrowhead",
  ASTRONOMER: "Astronomer",
  BANNER: "Banner",
  BARON: "Baron",
  BASEBALL_CARD: "Baseball Card",
  BLACKBOARD: "Blackboard",
  BLOODSTONE: "Bloodstone",
  BLUE_JOKER: "Blue Joker",
  BLUEPRINT: "Blueprint",
  BOOTSTRAPS: "Bootstraps",
  BRAINSTORM: "Brainstorm",
  BULL: "Bull",
  BURGLAR: "Burglar",
  BURNT_JOKER: "Burnt Joker",
  BUSINESS_CARD: "Business Card",
  CAMPFIRE: "Campfire",
  CANIO: "Canio",
  CARD_SHARP: "Card Sharp",
  CARTOMANCER: "Cartomancer",
  CASTLE: "Castle",
  CAVENDISH: "Cavendish",
  CEREMONIAL_DAGGER: "Ceremonial Dagger",
  CERTIFICATE: "Certificate",
  CHAOS_THE_CLOWN: "Chaos the Clown",
  CHICOT: "Chicot",
  CLEVER_JOKER: "Clever Joker",
  CLOUD_9: "Cloud 9",
  CONSTELLATION: "Constellation",
  CRAFTY_JOKER: "Crafty Joker",
  CRAZY_JOKER: "Crazy Joker",
  CREDIT_CARD: "Credit Card",
  DNA: "DNA",
  DELAYED_GRATIFICATION: "Delayed Gratification",
  DEVIOUS_JOKER: "Devious Joker",
  DIET_COLA: "Diet Cola",
  DRIVERS_LICENSE: "Driver's License",
  DROLL_JOKER: "Droll Joker",
  DRUNKARD: "Drunkard",
  DUSK: "Dusk",
  EGG: "Egg",
  EROSION: "Erosion",
  EVEN_STEVEN: "Even Steven",
  FACELESS_JOKER: "Faceless Joker",
  FIBONACCI: "Fibonacci",
  FLASH_CARD: "Flash Card",
  FLOWER_POT: "Flower Pot",
  FORTUNE_TELLER: "Fortune Teller",
  FOUR_FINGERS: "Four Fingers",
  GIFT_CARD: "Gift Card",
  GLASS_JOKER: "Glass Joker",
  GLUTTONOUS_JOKER: "Gluttonous Joker",
  GOLDEN_JOKER: "Golden Joker",
  GOLDEN_TICKET: "Golden Ticket",
  GREEDY_JOKER: "Greedy Joker",
  GREEN_JOKER: "Green Joker",
  GROS_MICHEL: "Gros Michel",
  HACK: "Hack",
  HALF_JOKER: "Half Joker",
  HALLUCINATION: "Hallucination",
  HANGING_CHAD: "Hanging Chad",
  HIKER: "Hiker",
  HIT_THE_ROAD: "Hit the Road",
  HOLOGRAM: "Hologram",
  ICE_CREAM: "Ice Cream",
  INVISIBLE_JOKER: "Invisible Joker",
  JOKER: "Joker",
  JOKER_STENCIL: "Joker Stencil",
  JOLLY_JOKER: "Jolly Joker",
  JUGGLER: "Juggler",
  LOYALTY_CARD: "Loyalty Card",
  LUCHADOR: "Luchador",
  LUCKY_CAT: "Lucky Cat",
  LUSTY_JOKER: "Lusty Joker",
  MAD_JOKER: "Mad Joker",
  MADNESS: "Madness",
  MAIL_IN_REBATE: "Mail-In Rebate",
  MARBLE_JOKER: "Marble Joker",
  MATADOR: "Matador",
  MERRY_ANDY: "Merry Andy",
  MIDAS_MASK: "Midas Mask",
  MIME: "Mime",
  MISPRINT: "Misprint",
  MR_BONES: "Mr. Bones",
  MYSTIC_SUMMIT: "Mystic Summit",
  OBELISK: "Obelisk",
  ODD_TODD: "Odd Todd",
  ONYX_AGATE: "Onyx Agate",
  OOPS_ALL_6S: "Oops! All 6s",
  PAREIDOLIA: "Pareidolia",
  PERKEO: "Perkeo",
  PHOTOGRAPH: "Photograph",
  POPCORN: "Popcorn",
  RAISED_FIST: "Raised Fist",
  RAMEN: "Ramen",
  RED_CARD: "Red Card",
  RESERVED_PARKING: "Reserved Parking",
  RIDE_THE_BUS: "Ride the Bus",
  RIFF_RAFF: "Riff-raff",
  ROCKET: "Rocket",
  ROUGH_GEM: "Rough Gem",
  RUNNER: "Runner",
  SATELLITE: "Satellite",
  SCARY_FACE: "Scary Face",
  SCHOLAR: "Scholar",
  SEANCE: "Seance",
  SEEING_DOUBLE: "Seeing Double",
  SELTZER: "Seltzer",
  SHOOT_THE_MOON: "Shoot the Moon",
  SHORTCUT: "Shortcut",
  SHOWMAN: "Showman",
  SIXTH_SENSE: "Sixth Sense",
  SLY_JOKER: "Sly Joker",
  SMEARED_JOKER: "Smeared Joker",
  SMILEY_FACE: "Smiley Face",
  SOCK_AND_BUSKIN: "Sock and Buskin",
  SPACE_JOKER: "Space Joker",
  SPARE_TROUSERS: "Spare Trousers",
  SPLASH: "Splash",
  SQUARE_JOKER: "Square Joker",
  STEEL_JOKER: "Steel Joker",
  STONE_JOKER: "Stone Joker",
  STUNTMAN: "Stuntman",
  SUPERNOVA: "Supernova",
  SUPERPOSITION: "Superposition",
  SWASHBUCKLER: "Swashbuckler",
  THE_DUO: "The Duo",
  THE_FAMILY: "The Family",
  THE_IDOL: "The Idol",
  THE_ORDER: "The Order",
  THE_TRIBE: "The Tribe",
  THE_TRIO: "The Trio",
  THROWBACK: "Throwback",
  TO_DO_LIST: "To Do List",
  TO_THE_MOON: "To the Moon",
  TRADING_CARD: "Trading Card",
  TRIBOULET: "Triboulet",
  TROUBADOUR: "Troubadour",
  TURTLE_BEAN: "Turtle Bean",
  VAGABOND: "Vagabond",
  VAMPIRE: "Vampire",
  WALKIE_TALKIE: "Walkie Talkie",
  WEE_JOKER: "Wee Joker",
  WILY_JOKER: "Wily Joker",
  WRATHFUL_JOKER: "Wrathful Joker",
  YORICK: "Yorick",
  ZANY_JOKER: "Zany Joker",
};

const JOKERS_LIST = Object.values(JOKERS_MAP);

export { JOKERS_MAP, JOKERS_LIST };
